language: python
cache: pip
dist: bionic

addons:
  apt:
    packages:
      - sqlite3
      - gdal-bin

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel
  - pip install $DJANGO
  - pip install -U -r requirements-test.txt

install:
  - python setup.py -q develop

before-script:
  - >
    openwisp-utils-qa-checks \
        --migration-path ./openwisp_notifications/migrations/ \
        --migration-module openwisp_notifications

script:
  - coverage run -a --source=openwisp_notifications runtests.py

after_success:
  - coveralls